name: Retrieves artifact information
description: Retrieves artifact information
author: nosamad

inputs:
  version:
    description: Version string
    default: ''
    required: false
  platform:
    description: Platform string
    default: ''
    required: false

outputs:
  version:
    description: Effective version string
    value: ${{ steps.set-artifact-info.outputs.version }}
  buildtime:
    description: Build time string
    value: ${{ steps.set-artifact-info.outputs.buildtime }}
  platform-id:
    description: Platform identifier string
    value: ${{ steps.set-artifact-info.outputs.platform-id }}

runs:
 using: composite

 steps:
   - name: Check environment
     run: |
       command -V date
       command -V git
       command -V sed
       command -V tr
       command -V bash
     shell: sh
     
   - name: Set Artifact information
     id: set-artifact-info
     env:
      VERSION: ${{ inputs.version }}
      PLATFORM: ${{ inputs.platform }}
     run: |
       platform_id="${PLATFORM:-${RUNNER_OS}}"
       platform_id="$(echo "${platform_id}" | tr '[:upper:]' '[:lower:]')"
       platform_id="$(echo "${platform_id}" | tr \/ _)"
       echo "::set-output name=platform-id::${platform_id}"

       export TZ=UTC

       SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git log -1 --pretty='%ct')}"
       echo "SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}" >> "${GITHUB_ENV}"

       static_version="$VERSION"
       if [[ -z "${static_version}" ]] || [[ "${static_version}" == *-dev ]]; then
         git_date="$(date --utc --date "@${SOURCE_DATE_EPOCH}" +'%Y%m%d%H%M%S')"
         git_commit="$(git log -1 --pretty='%h')"
         static_version="0.0.0-${git_date}-${git_commit}"
       fi
       echo "::set-output name=version::${static_version}"
       
       buildtime="$(date -u -d "@${SOURCE_DATE_EPOCH}" --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/')"
       echo "::set-output name=buildtime::${buildtime}"
     shell: bash
